image: alpine/latest
packages:
  - go
  - python3
sources:
  - https://github.com/emersion/go-varlink
  - https://github.com/varlink/python
tasks:
  - build: |
      cd go-varlink
      go build -race -v ./...
  - test: |
      cd go-varlink
      go test -race ./...
  - gofmt: |
      cd go-varlink
      test -z $(gofmt -l .)
  - client-certification: |
      cd go-varlink
      PYTHONPATH=../python/ python3 -m varlink.tests.test_certification --varlink=tcp:127.0.0.1:12345 &
      PID=$!
      for i in {1..12}; do
          nc -z 127.0.0.1 12345 && break
          sleep 0.25
      done
      go run ./cmd/certification client -protocol tcp -socket 127.0.0.1:12345
      kill $PID 2>/dev/null || true
